In [1]:
import pandas as pd
from nltk.tokenize import word_tokenize

In [2]:
positive_lexicon = pd.read_csv('data/lexicon/InSet/positive.tsv',sep='\t')
negative_lexicon = pd.read_csv('data/lexicon/InSet/negative.tsv',sep='\t')

In [3]:
lexicon = positive_lexicon.append(negative_lexicon,ignore_index=True)

In [4]:
content = (open("data/lexicon/swear-words.txt", "r")).read()
swear_words = content.split("\n")

In [5]:
weight_swear = [-5 for i in range(len(swear_words))]
swear_lexicon = pd.DataFrame(list(zip(swear_words,weight_swear)),columns =['word','weight'])

In [6]:
add_lexi = pd.read_csv('data/lexicon/agusmakmun/sentiment.csv')
lexi_word = lexicon['word'].to_list()

In [7]:
add_word = []
add_weight = []
for i in range(0,len(add_lexi)):
    if (add_lexi['word'][i] not in lexi_word):
        add_word.append(add_lexi['word'][i])
        add_weight.append(add_lexi['weight'][i])

addition_lexicon = pd.DataFrame(list(zip(add_word,add_weight)),columns =['word','weight'])

In [8]:
lexicon = lexicon.append(addition_lexicon,ignore_index = True)
lexicon = lexicon.append(swear_lexicon,ignore_index = True)

In [9]:
positive_lexicon_2 = pd.read_csv('data/lexicon/ahalimidev/lexicon_positive.csv')
negative_lexicon_2 = pd.read_csv('data/lexicon/ahalimidev/lexicon_negative.csv')
lexicon_2 = positive_lexicon_2.append(negative_lexicon_2,ignore_index=True)
lexi_word_2 = lexicon['word'].to_list()

In [10]:
add_word_2 = []
add_weight_2 = []
for i in range(0,len(add_lexi)):
    if (lexicon_2['word'][i] not in lexi_word_2):
        add_word.append(lexicon_2['word'][i])
        add_weight.append(lexicon_2['weight'][i])

addition_lexicon_2 = pd.DataFrame(list(zip(add_word,add_weight)),columns =['word','weight'])

In [11]:
lexicon = lexicon.append(addition_lexicon_2,ignore_index = True)

In [12]:
lexicon

             word  weight
0             hai       3
1         merekam       2
2       ekstensif       3
3       paripurna       1
4          detail       2
...           ...     ...
11927    waktunya      -2
11928  waspadalah      -2
11929         wow       3
11930         wtf      -3
11931       yatim      -2

[11932 rows x 2 columns]

In [13]:
def number_of_words(x):
    words = word_tokenize(x['word'])
    number = len(words)
    return number

lexicon['number_of_words'] = lexicon.apply(lambda x: number_of_words(x),axis=1)
lexicon  = lexicon.reset_index(drop=True)
lexicon[lexicon['number_of_words'] == 3]

                           word  weight  number_of_words
117        jalan bebas hambatan       2                3
364              asah asih asuh       2                3
574                lunas (kapal       2                3
1106       mencium telapak kaki       1                3
1501          naik ke pelaminan       3                3
1853            naik ke pelamin       3                3
1871          cium telapak kaki       1                3
1904            minta kpd tuhan       3                3
1927         jalan bebas hambat       2                3
2073              acuh tak acuh       4                3
3609         putus tali gantung      -2                3
3678           berlalu dr dunia      -5                3
3680  menarik napas penghabisan      -5                3
3713       jalan bebas hambatan      -1                3
3777           tidak masuk akal      -4                3
4452              acuh tak acuh      -3                3
5771         jalan bebas hambat      -1                3
6025          tarik napas habis      -5                3
6089              lalu dr dunia      -5                3
6236               lunas (kapal      -3                3
6525              asan tak asan      -5                3
6917            buang air besar      -5                3
8164             ikan kena tuba      -4                3
8305      menyerahkan jiwa raga      -4                3
8439            buang air kecil      -3                3
9788         cacing rambut kuda      -4                3

In [14]:
lexicon.to_csv('data/lexicon/full_lexicon.csv',index=False)